In [2]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [3]:
kagglehub.dataset_download(  "undefinenull/million-song-dataset-spotify-lastfm")

Downloading to /root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/1.archive...

100%|██████████| 639M/639M [00:30<00:00, 22.0MB/s]

Extracting files...

'/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1'

In [4]:
import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [5]:
data_path = Path("/root/.cache/kagglehub/datasets/undefinenull/million-song-dataset-spotify-lastfm/versions/1")
# songs_data_path = data_path / 'Music Info.csv'
users_data_path = data_path / 'User Listening History.csv'

In [6]:

df_users = pd.read_csv(users_data_path)

In [7]:
df_users.head()

             track_id                                   user_id  playcount
0  TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
1  TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
2  TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
3  TRTUCUY128F92E1D24  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
4  TRHDDQG12903CB53EE  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1

In [8]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9711301 entries, 0 to 9711300
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   track_id   object
 1   user_id    object
 2   playcount  int64
dtypes: int64(1), object(2)
memory usage: 222.3+ MB

In [9]:
df_users.describe()

          playcount
count  9.711301e+06
mean   2.630946e+00
std    5.706324e+00
min    1.000000e+00
25%    1.000000e+00
50%    1.000000e+00
75%    2.000000e+00
max    2.948000e+03

In [10]:
df_users.duplicated(subset=["user_id","track_id"]).sum()

np.int64(0)

In [11]:
df_users.isna().sum()

track_id     0
user_id      0
playcount    0
dtype: int64

In [12]:
# unique users in the datase
df_users.loc[:,"user_id"].nunique()

962037

In [13]:
df_users["user_id"].unique()

array(['b80344d063b5ccb3212f76538f3d9e43d87dca9e',
       '85c1f87fea955d09b4bec2e36aee110927aedf9a',
       'bd4c6e843f00bd476847fb75c47b4fb430a06856', ...,
       'ca99d94daa9d5231643a08aac2f3bfb645e73b09',
       'cf8289419383259189afe6bb50c5115fd84f1064',
       'b7815dbb206eb2831ce0fe040d0aa537e2e800f7'], dtype=object)

In [14]:
df_users["track_id"].nunique()

30459

In [29]:
# top 10 palyed songs
top_10_songs=(
    df_users
    .loc[:,"track_id"]
    .value_counts()
    .head(10)
)

In [30]:
top_10_songs[top_10_songs.index == "TRWAQOC12903CB84CA"]

track_id
TRWAQOC12903CB84CA    27222
Name: count, dtype: int64

In [16]:
 df_users.groupby("track_id").size().sort_values(ascending=False).head(10)

track_id
TRONYHY128F92C9D11    80656
TRUFTBY128F93450B8    39529
TRXWAZC128F9314B3E    30873
TRCPXID128F92D5D3C    30057
TRGCHLH12903CB7352    29708
TROMKCG128F9320C09    28735
TRPFYYL128F92F7144    28412
TRPGPDK12903CCC651    27276
TRWAQOC12903CB84CA    27222
TRAALAH128E078234A    26689
dtype: int64

In [17]:
df_users

,track_id,user_id,playcount
0,TRIRLYL128F42539D1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
1,TRFUPBA128F934F7E1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
2,TRLQPQJ128F42AA94F,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
3,TRTUCUY128F92E1D24,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
4,TRHDDQG12903CB53EE,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
...,...,...,...
9711296,TRBKFKL128E078ED76,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,1
9711297,TRYFXPG128E078ECBD,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,1
9711298,TROBUUZ128F4263002,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,1
9711299,TROEWXC128F148C83E,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,1
9711300,TROHQNO128F146ECCB,b7815dbb206eb2831ce0fe040d0aa537e2e800f7,1

In [18]:
top_10_palyed_songs = df_users.groupby("track_id")["playcount"].agg("sum").sort_values(ascending=False).head(10)

In [19]:
top_10_palyed_songs.head()

track_id
TRONYHY128F92C9D11    527893
TRUFTBY128F93450B8    111615
TRZNAHL128F9327D5A    111596
TRCPXID128F92D5D3C     91461
TRPGPDK12903CCC651     91448
Name: playcount, dtype: int64

In [20]:
#  most playcounts for songs
pd.concat([top_10_songs,top_10_palyed_songs],axis=1)

                      count  playcount
track_id
TRONYHY128F92C9D11  80656.0   527893.0
TRUFTBY128F93450B8  39529.0   111615.0
TRXWAZC128F9314B3E  30873.0    87745.0
TRCPXID128F92D5D3C  30057.0    91461.0
TRGCHLH12903CB7352  29708.0    78443.0
TROMKCG128F9320C09  28735.0    87050.0
TRPFYYL128F92F7144  28412.0    85079.0
TRPGPDK12903CCC651  27276.0    91448.0
TRWAQOC12903CB84CA  27222.0        NaN
TRAALAH128E078234A  26689.0    76893.0
TRZNAHL128F9327D5A      NaN   111596.0

In [37]:
# users with most different types of songs listedned
most_diverse_listeners = df_users.groupby(["user_id"])["track_id"].agg("count").sort_values(ascending=False).head(5)

In [38]:
most_diverse_listeners

user_id
ec6dfcf19485cb011e0b22637075037aae34cf26    784
4e11f45d732f4861772b2906f81a7d384552ad12    384
726da71c2c2ea119119a7957517fccd028d1be76    376
113255a012b2affeab62607563d03fbdf31b08e7    367
7adec7f006cb09482d36609d205293d8b61f030e    366
Name: track_id, dtype: int64

In [48]:
most_active_users = df_users.groupby("user_id")["playcount"].agg("sum").sort_values(ascending=False).head(5)
most_active_users

user_id
1854daf178674bbac9a8ed3d481f95b76676b414    2953
944cdf52364f45b0edd1c972b5a73d3a86b09c6a    2046
6a8a142084a4818c0dcac48bdfb3c39deacf5168    1942
93158e3983ffc8945e25c793d93d6b67d46cae9d    1845
f0b5c784daaa3c7d50acbb3723c7dd649db2b231    1841
Name: playcount, dtype: int64

In [52]:
pd.concat([most_diverse_listeners,most_active_users],axis=1).head(40)

                                          track_id  playcount
user_id
ec6dfcf19485cb011e0b22637075037aae34cf26     784.0        NaN
4e11f45d732f4861772b2906f81a7d384552ad12     384.0        NaN
726da71c2c2ea119119a7957517fccd028d1be76     376.0        NaN
113255a012b2affeab62607563d03fbdf31b08e7     367.0        NaN
7adec7f006cb09482d36609d205293d8b61f030e     366.0        NaN
1854daf178674bbac9a8ed3d481f95b76676b414       NaN     2953.0
944cdf52364f45b0edd1c972b5a73d3a86b09c6a       NaN     2046.0
6a8a142084a4818c0dcac48bdfb3c39deacf5168       NaN     1942.0
93158e3983ffc8945e25c793d93d6b67d46cae9d       NaN     1845.0
f0b5c784daaa3c7d50acbb3723c7dd649db2b231       NaN     1841.0